proton-install - reinstall old proton version if new if not ok

diff --git a/enshrd_backupgrade b/enshrd_backupgrade
--- a/enshrd_backupgrade
+++ b/enshrd_backupgrade
@@ -88,9 +88,9 @@ fi
 # Proton Update if set
 if [ "$_PROTON_UPDATE" = "true" ]; then
   if type proton-update >/dev/null 2>&1; then
-    proton-update || _LOGTHIS WARN "Tried to reinstall previous Proton version"
+    proton-update || { _LOGTHIS FAIL "Proton test failed, server blocked" && exit 1; }
     else
-    _LOGTHIS FAIL "Proton Update script not found"
+    _LOGTHIS WARN "Proton Update script not found.. skip"
 fi
 _LOGTHIS INFO "Restarting service: $_SERVICEFILE"
 sudo systemctl start $_SERVICEFILE
@@ -99,7 +99,7 @@ counter="0"
 while ! grep -q SVN ${_GAMEDIR}/logs/enshrouded_server.log; do
 	sleep 3
 	counter=$((counter+1))
-	[ "$counter" = 20 ] && break
+	[ "$counter" = 20 ] && _LOGTHIS FAIL "Service did not restart properly" && exit 1
 done
 _LOGTHIS END "Enshrouded Server [Version:$(grep SVN ${_GAMEDIR}/logs/enshrouded_server.log | awk '{print $NF}')] - Backup/Update Complete! "
 
