proton-update corrected

diff --git a/enshrd_backupgrade b/enshrd_backupgrade
--- a/enshrd_backupgrade
+++ b/enshrd_backupgrade
@@ -49,9 +49,10 @@ type enshrd_query >/dev/null || { _LOGTHIS FAIL "Script 'enshrd_query' not found
 # SteamCMD update function
 _ENSHRDUPDATE(){
 _LOGTHIS INFO "Starting SteamCMD Game Update"
-$_STEAMCMD +@sSteamCmdForcePlatformType windows +force_install_dir $_GAMEDIR +login anonymous +app_update 2278520 +quit > ${_WKGDIR}/steamcmd-last-update.txt && \
-_LOGTHIS SUCCESS "SteamCMD Update Success! [log: ${_WKGDIR}/steamcmd-last-update.txt]" || \
-_LOGTHIS FAIL "SteamCMD Update Failed [log: ${_WKGDIR}/steamcmd-last-update.txt]"
+_LOGTHIS INFO "SteamCMD Log: ${_WKGDIR}/steamcmd-last-update.log"
+$_STEAMCMD +@sSteamCmdForcePlatformType windows +force_install_dir $_GAMEDIR +login anonymous +app_update 2278520 +quit > ${_WKGDIR}/steamcmd-last-update.log && \
+_LOGTHIS INFO "SteamCMD Update Success!" || \
+_LOGTHIS FAIL "SteamCMD Update Failed.."
 }
 
 # Base Informations collect
@@ -90,7 +91,7 @@ fi
 # Proton Update if set
 if [ "$_PROTON_UPDATE" = "true" ]; then
   if type proton-update >/dev/null 2>&1; then
-    proton-update || { _LOGTHIS FAIL "Proton check failed, Server inconsistency.." && exit 1; }
+    proton-update || { _LOGTHIS END_FAIL "Proton check failed, Server inconsistency.." && exit 1; }
   else
     _LOGTHIS WARN "Script 'proton-update' not found: skip.."
   fi
@@ -104,5 +105,5 @@ while ! grep -q SVN ${_GAMEDIR}/logs/enshrouded_server.log; do
 	counter=$((counter+1))
 	[ "$counter" = 20 ] && _LOGTHIS END_FAIL "Service did not restart properly" && exit 1
 done
-_LOGTHIS END_SUCCESS "Enshrouded Server [Version:$(grep SVN ${_GAMEDIR}/logs/enshrouded_server.log | awk '{print $NF}')] - Backup/Update Complete! "
+_LOGTHIS END "Enshrouded Server [Version:$(grep SVN ${_GAMEDIR}/logs/enshrouded_server.log | awk '{print $NF}')] - Backup/Update Complete! "
 
